time_horizon: 10
time_step: 0.05
interval: 1
number_obstacles: 3
lower_limits: 
  state: [-10, -10, -10]
  action: [-7, -0.5]
  slack: [0]
upper_limits: 
  state: [10, 10, 10]
  action: [7.0, 0.5]
  slack: [inf]
model_length: 0.3
model_radius: 0.1
debug: False
